[ AutoCAD - Wed Jun 18 13:04:34 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadMLine 000000002b8d0108>
; IAcadMLine: IAcadMLine Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fca2308>
;   Coordinates = (9.15538 14.989 0.0 18.7947 10.0057 0.0 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000037abb2b8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037fa5d28>
;   Justification = 0
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   MLineScale = 1.0
;   ObjectID (RO) = 58
;   ObjectID32 (RO) = 58
;   ObjectName (RO) = "AcDbMline"
;   OwnerID (RO) = 59
;   OwnerID32 (RO) = 59
;   PlotStyleName = "ByLayer"
;   StyleName (RO) = "STANDARD"
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037fa5e40>
;   Visible = -1
