[ AutoCAD - Wed Jun 18 13:08:02 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadHelix 000000002bb90198>
; IAcadHelix: IAcadSpring Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fb02308>
;   BaseRadius = 1.36885
;   Constrain = 1
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002e85d628>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Height = 1.0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000035c72478>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   ObjectID (RO) = 54
;   ObjectID32 (RO) = 54
;   ObjectName (RO) = "AcDbHelix"
;   OwnerID (RO) = 55
;   OwnerID32 (RO) = 55
;   PlotStyleName = "ByLayer"
;   Position = (2.25405 13.3778 0.0)
;   TopRadius = 6.82783
;   TotalLength (RO) = 77.4916
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000035c726b0>
;   TurnHeight = 0.333333
;   Turns = 3.0
;   TurnSlope (RO) = 1.38962
;   Twist = 0
;   Visible = -1
