[ AutoCAD - Wed Jun 18 12:33:52 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 00000000358675a8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffc2308>
;   Area (RO) = 121.668
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (28.9217 8.88171 30.6459 5.29844 34.1471 3.41302 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000352ed638>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000035aa4138>
;   Layer = "0"
;   Length (RO) = 39.7655
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Extrusion = (0.0 0.0 1.0)
;   ObjectID (RO) = 54
;   ObjectID32 (RO) = 54
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 55
;   OwnerID32 (RO) = 55
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000035aa47f0>
;   Visible = -1
